#!/usr/bin/env python3
"""Generate and check provenance-tag coverage for reference files."""
from __future__ import annotations

from dataclasses import dataclass
import argparse
import re
import sys
from pathlib import Path


TAG_PATTERNS = {
    "author_verified": re.compile(r"\[AUTHOR-VERIFIED\]"),
    "docs_only": re.compile(r"\[DOCS-ONLY[^\]]*\]"),
    "verified_web": re.compile(r"\[VERIFIED-web\]"),
    "needs_hw_test": re.compile(r"\[NEEDS-HW-TEST\]"),
}


@dataclass(frozen=True)
class CoverageEntry:
    path: Path
    lines: int
    author_verified: int
    docs_only: int
    verified_web: int
    needs_hw_test: int

    @property
    def total_tags(self) -> int:
        return self.author_verified + self.docs_only + self.verified_web + self.needs_hw_test

    @property
    def status(self) -> str:
        if self.total_tags == 0:
            return "untagged"
        if self.author_verified and self.docs_only == 0 and self.verified_web == 0 and self.needs_hw_test == 0:
            return "author-verified"
        return "partial"


def collect_entries(root: Path) -> list[CoverageEntry]:
    refs_dir = root / "references"
    entries = []
    for path in sorted(refs_dir.glob("*.md")):
        if path.name == "provenance-coverage.md":
            continue
        text = path.read_text(encoding="utf-8")
        entries.append(CoverageEntry(
            path=path.relative_to(root),
            lines=len(text.splitlines()),
            author_verified=len(TAG_PATTERNS["author_verified"].findall(text)),
            docs_only=len(TAG_PATTERNS["docs_only"].findall(text)),
            verified_web=len(TAG_PATTERNS["verified_web"].findall(text)),
            needs_hw_test=len(TAG_PATTERNS["needs_hw_test"].findall(text)),
        ))
    return entries


def render_markdown(entries: list[CoverageEntry]) -> str:
    total = len(entries)
    tagged = sum(1 for entry in entries if entry.total_tags)
    author_verified = sum(entry.author_verified for entry in entries)
    docs_only = sum(entry.docs_only for entry in entries)
    verified_web = sum(entry.verified_web for entry in entries)
    needs_hw_test = sum(entry.needs_hw_test for entry in entries)

    lines = [
        "# Provenance Coverage",
        "",
        "This table tracks confidence-tag coverage across `references/*.md`. It is generated by",
        "`scripts/provenance_coverage.py`; update it with `python scripts/provenance_coverage.py --write`.",
        "",
        "The table is a coverage map, not an audit certificate. Untagged files can still contain cited, useful",
        "engineering guidance, but they should not be read as author-executed evidence.",
        "",
        f"Summary: {tagged}/{total} reference files contain provenance tags; "
        f"{author_verified} `[AUTHOR-VERIFIED]`, {docs_only} `[DOCS-ONLY]`, "
        f"{verified_web} `[VERIFIED-web]`, {needs_hw_test} `[NEEDS-HW-TEST]` tags.",
        "",
        "| Reference | Lines | AUTHOR-VERIFIED | DOCS-ONLY | VERIFIED-web | NEEDS-HW-TEST | Status |",
        "|---|---:|---:|---:|---:|---:|---|",
    ]
    for entry in entries:
        lines.append(
            f"| `{entry.path.as_posix()}` | {entry.lines} | {entry.author_verified} | "
            f"{entry.docs_only} | {entry.verified_web} | {entry.needs_hw_test} | {entry.status} |"
        )
    lines.append("")
    return "\n".join(lines)


def main(argv: list[str]) -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--write", action="store_true", help="write references/provenance-coverage.md")
    parser.add_argument("--check", action="store_true", help="fail if checked-in table is stale")
    args = parser.parse_args(argv)

    root = Path(__file__).resolve().parents[1]
    out = root / "references" / "provenance-coverage.md"
    rendered = render_markdown(collect_entries(root))

    if args.write:
        out.write_text(rendered, encoding="utf-8")
    elif args.check:
        if not out.exists():
            print(f"{out.relative_to(root)} is missing; run python scripts/provenance_coverage.py --write")
            return 1
        current = out.read_text(encoding="utf-8")
        if current != rendered:
            print(f"{out.relative_to(root)} is stale; run python scripts/provenance_coverage.py --write")
            return 1
    else:
        print(rendered, end="")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
